#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="static-stack"
SCRIPT_DES=$'Script for standing up statis resources. Configure \e[3m.env\e[0m file before executing.'
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/.env

# Example Usage:
# >$     static-stack --action <create | update | delete> \

#   NOTE: ``--action`` defaults to `create` if not supplied

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action|-action|--a|-a)
            ACTION="$2"
            shift
            shift 
            ;;
        --help|-help|--h|-h)
            help
            exit 0
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ -z "$ACTION" ]
then
    log "No \e[3m--action\e[0m specified. Defaulting to \e[1mcreate\e[0m"
    ACTION="create"
fi

cp $PROJECT_DIR/cf/static.yml ./static.yml

CERTIFICATE_ARN="arn:aws:acm:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:certificate/$CERTIFICATE_ID"
if [ "$ACTION" == "create" ]
then
    log "Creating \e[1m${APPLICATION^}-${STATIC_STACK}\e[0m"
    aws cloudformation create-stack \
        --stack-name "${APPLICATION^}-${STATIC_STACK}" \
        --template-body file://static.yml \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameters ParameterKey=applicationName,ParameterValue=$APPLICATION \
                        ParameterKey=hostedZoneId,ParameterValue="$HOSTED_ZONE_ID" \
                        ParameterKey=certificateArn,ParameterValue="$CERTIFICATE_ARN" \
                        ParameterKey=domainName,ParameterValue="$DOMAIN"
elif [ "$ACTION" == "update" ]
then
    log "Updating \e[1m${APPLICATION^}-${STATIC_STACK}\e[0m"
    aws cloudformation update-stack \
        --stack-name "${APPLICATION^}-${STATIC_STACK}" \
        --template-body file://static.yml \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameters ParameterKey=applicationName,ParameterValue=$APPLICATION \
                        ParameterKey=hostedZoneId,ParameterValue="$HOSTED_ZONE_ID" \
                        ParameterKey=certificateArn,ParameterValue="$CERTIFICATE_ARN" \
                        ParameterKey=domainName,ParameterValue="$DOMAIN"
elif [ "$ACTION" == "delete" ]
then
    log "Deleting \e[1m${APPLICATION^}-${STATIC_STACK}\e[0m"
    aws cloudformation delete-stack \
        --stack-name "${APPLICATION^}-${STATIC_STACK}"
else
    log "Action not understood"
fi

rm ./static.yml